![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Tartiblash (`Sorting`)

In [ ]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementlardan tashkil topgan massiv
arr

array([0.00154748, 0.95231861, 0.52353173, 0.78106709])

### `sort` funkiyasi

In [ ]:
# 1 usul
sorted_arr = np.sort(arr) # arr massivini tartiblangan ko'rinishini sorted_arr joylaydi
sorted_arr

array([0.00154748, 0.52353173, 0.78106709, 0.95231861])

In [ ]:
#  2 usul
arr.sort() # arr ning tartiblangan ko'rinishi
arr

array([0.00154748, 0.52353173, 0.78106709, 0.95231861])

In [ ]:
# teskari tartiblash
rev_arr = -np.sort(-arr) # teskari tartibdagi arr
rev_arr

array([0.95231861, 0.78106709, 0.52353173, 0.00154748])

In [ ]:
# 2 D array (massiv)
arr2d = np.random.randn(2, 4) # (2, 4) random massiv
arr2d

array([[ 0.39234394,  0.06630415,  0.68868407, -0.14314612],
       [-0.86193768, -0.48095979,  0.80620653, -0.09093883]])

In [ ]:
# axis = 0 --> Qator
row_srt = np.sort(arr2d, axis=0) # arr2d ning xar bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[-0.86193768, -0.48095979,  0.68868407, -0.14314612],
       [ 0.39234394,  0.06630415,  0.80620653, -0.09093883]])

In [ ]:
# axis =1 --> Ustun
col_srt =np.sort(arr2d, axis=1) # arr2d ning xar bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[-0.14314612,  0.06630415,  0.39234394,  0.68868407],
       [-0.86193768, -0.48095979, -0.09093883,  0.80620653]])