![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science va Sun'iy Intellekt Praktikum

## Ma'lumotlar tahlili. 
## 2.1. NumPy kutubxonasi bilan ishlash

### NumPy kutubxonasini chaqirib olish

In [ ]:
import numpy as np

### 2.1.3. Massivga yo'naltirilgan dasturlash

### Mantiqiy shart operatorlarni massiv operator sifatida qo'llash

### Shart operatori sifatida `where` dan foydalanish

### Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: `xarr` va `yarr`. Agarda shart `True`ni qanoatlantirsa `xarr` elementini qabul qilgan aksincha esa `yarr` elementini qabul qilgan yangi massiv hosil qilinsin.

In [ ]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [ ]:
# Shart
cond = np.array([True, False, True, True, False])

In [ ]:
# where
result = np.where(cond, xarr, yarr) # cond==True : xarr elementi, cond==False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [ ]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[-1.6297284 , -0.54502   , -1.62194039,  0.21950899],
       [-1.02568231, -1.22287873, -3.35638726,  1.38844975],
       [ 0.29573755, -1.474369  , -0.87661759,  0.50263388],
       [ 0.5828061 , -1.80441975, -0.58818259,  1.05593611]])

In [ ]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[-2, -2, -2,  2],
       [-2, -2, -2,  2],
       [ 2, -2, -2,  2],
       [ 2, -2, -2,  2]])